### ISSUE TITLE
Lua modules works in half

### ISSUE THREAD

**Issue by ParadoxRB** [COVESA/ramses-logic#39] opened 2022-02-22 15:22 UTC
I tried to use LuaModules to define interfaces for some scripts to keep consistent connection between them.
After it was unsuccessful I tried the **documentation version** of LuaModules and it ended up with the same results.

It is possible to access the deepest table properties (leaves), but the full table cannot be used as an interface assignment.
Alternatively, I've tried assigning the module to a global value in init() and then to an I/O in interface(), the results are the same.

The error messages end with an unknown property that I wanted to assign in run().

Ramses: 27.0.115
RLogic: 0.14.2

**Comment by AchimStremplat** [comment] 2022-02-22 15:27
To reproduce, try the example [here](https://ramses-logic.readthedocs.io/en/latest/lua_syntax.html#using-lua-modules). The "coalaStruct" seems to be empty in the "interface()" function. 

If done in Ramses Composer, the error message is "lua: error: Unexpected property 'weight' while assigning values to struct ''!" for the script trying to make use of the "coalaStruct".

**Comment by violinyanev** [comment] 2022-02-23 17:07
Aww... that's a big whoopsie. Will look into it. Thanks for the through report!

**Comment by violinyanev** [comment] 2022-03-03 09:33
Confirmed, this is a bug related to environment sandboxing... Will fix in upcoming release

**Comment by violinyanev** [comment] 2022-03-14 09:35
@ParadoxRB @AchimStremplat the bug is fixed in v0.15.0. Give it a shot! Thanks for reporting.

**Closed by violinyanev** 2022-03-14 09:35 UTC
Labels: bug
